service: flutter-gpt

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-southeast-1
  memorySize: 512
  timeout: 180
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"

package:
  exclude:
    - .npmignore
    - .vscode/**
    - .github/**
    - (*).json
    - (*).ipynb
    - node_modules/**
    - venv/**
    - LICENSE
    - test/**
    - site/**
    - html_files_index.txt
    - create_embeddings.py

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true

functions:
  ask-question:
    handler: handler.ask_question
    # https://www.serverless.com/framework/docs/providers/aws/guide/functions#lambda-function-urls
    url:
      # Allow CORS for all requests from any origin
      cors:
        allowedOrigins:
          - "*"
          #- https://url1.com
          #- https://url2.com
        allowedMethods:
          - POST
